### PR TITLE
[WIP] Add UI for upgrading to Cloud 6

### PR DESCRIPTION
**Pull request by vwallfahrer**

### CODE REVIEW

**Comment by jsuchome** [comment]
We need this page in Cloud5 code (https://github.com/crowbar/barclamp-crowbar)

**Comment by rsalevsky** [comment]
As we discussed in the workshop upgrading the nodes is part of cloud 6, the only thing what we need in cloud 5 is the part of@nkrinner which disables all the OpenStack services.

**Comment by jsuchome** [comment]
@rsalevsky no, this should be the part that would lead to @nkrinner's state change.

See point 1 at https://etherpad.nue.suse.com/p/cloud-5-to-6-upgrade and https://trello.com/c/8aq8iOkG/597-3-s33p2-add-cloud-5-ui-to-start-upgrade-process

**Comment by rsalevsky** [comment]
Then the implementation is wrong, see line 10 in the etherpad. Transfer the nodes into the upgrade state should be done on a utils page. The upgrade button on the nodes page should upgrade the node see step 9.

**Comment by tboerger** [comment]
1) This is the wrong repository as we are not building anything on SUSE-Cloud org
2) This navigation item should be at Utils, this is nothing for the general node actions

**Pull request closed without merging**
